ibm-messaging/kafka-java-vertx-starter

- CLA.md
> Add CLA.md

- pom.xml
- src/main/java/kafka/vertx/demo/websocket/WebsocketVerticle.java
Simple enhancements to the Maven POM
> Improve POM

- README.md
Signed-off-by: Grace Jansen <grace.jansen1@ibm.com>
> feat: Update README with updated jar name

- src/main/java/kafka/vertx/demo/PeriodicProducer.java
> fix: Add producer exception handler

- README.md
- src/main/java/kafka/vertx/demo/PeriodicProducer.java
- src/main/java/kafka/vertx/demo/WebSocketServer.java
- src/main/resources/kafka.properties
> feat: Make topic configurable

- src/main/java/kafka/vertx/demo/PeriodicProducer.java
- src/main/java/kafka/vertx/demo/WebSocketServer.java
> feat: Allow relative path for keystore/truststore

- pom.xml
> feat: Update to use vertx 4 milestone5

- pom.xml
- src/main/java/kafka/vertx/demo/Main.java
- src/main/resources/project.properties
Remove version from jar name and print on startup instead.
> feat: Remove version from jar name

- .github/workflows/java-pr-jobs.yml
- pom.xml
- src/main/java/kafka/vertx/demo/Main.java
- src/main/java/kafka/vertx/demo/PeriodicProducer.java
- src/main/java/kafka/vertx/demo/WebSocketServer.java
- src/test/java/kafka/vertx/demo/MainTest.java
- src/test/resources/testConfig/kafka.properties
- src/test/resources/testConfig/myconfig.properties
Update the properties path options so it accepts a directory. Use the properties path to determine the absolute path for the truststore and keystore.
> Properties path as dir

- kafka.properties
> feat: Include additional security options in props

- src/main/java/kafka/vertx/demo/PeriodicProducer.java
> feat: Send error to frontend if produce fails

- ui/e2e/features/basic_interactions.feature
- ui/e2e/features/step_definitions/consumer.js
- ui/e2e/features/step_definitions/index.js
- ui/e2e/features/step_definitions/producer.js
- ui/jest-playwright.config.js
- ui/src/DevUtils/MockVertx/MockVertxServer.js
- ui/src/Elements/Message/Message.view.js
Completes the e2e tests for the UI, running against the 
mock vertx websocket server.
Contributes to: matthew-chirgwin/kafka-java-vertx-starter#60
Signed-off-by: Andrew Borley <borley@uk.ibm.com>
> feat: Complete UI e2e tests

- .github/workflows/github-build-release.yml
**READY**
Contributes to: #30
* When opening this PR, the raiser should set the title of this PR to the first line of their desired commit message, e.g:
```
fix: release workflow trigger
```
* The reviewer should ensure that the first commit message field is of this form when performing the `squash and merge` from this page.
```
- updates release workflow to trigger on matching tag format on master
branch only
Contributes to: #30
Signed-off-by: Matthew Chirgwin <chirmatt@uk.ibm.com>
```
* The reviewer should copy the above text into the extended description field when performing the `squash and merge` from this page.
> fix: release workflow trigger

- ui/package.json
**READY**
```
feat: Added chore option to git linter
```
```
Added the option of "chore" to the git linter to allow for
it to be used in the title of a git commit.
Further details of the code going into the commit
Closes: 38
Signed off by: William Treston <w.treston@gmail.com>
```
> feat: Added chore option to git linter

- pom.xml
Contributes to #67
**READY/IN DEVELOPMENT/HOLD**
* When opening this PR, the raiser should set the title of this PR to the first line of their desired commit message, e.g:
```
feat|fix|docs|style|refactor|perf|test|chore: changed function X
```
* The reviewer should ensure that the first commit message field is of this form when performing the `squash and merge` from this page.
```
Further details of the code going into the commit
Contributes to: #XYZ
Closes: #XYZ
Signed-off-by: Your Name <email@address.com>
```
* The reviewer should copy the above text into the extended description field when performing the `squash and merge` from this page.
> feat: Update Kafka version to 2.6.0

- pom.xml
> feat: update kafka version to 2.6.2

- pom.xml
**READY**
* When opening this PR, the raiser should set the title of this PR to the first line of their desired commit message, e.g:
```
feat: Update to Kafka 2.8.0
```
* The reviewer should ensure that the first commit message field is of this form when performing the `squash and merge` from this page.
```
- Changed Kafka version to 2.8.0 in pom
Contributes to: mhub/qp-planning#6996
Signed-off-by: Zoe Gathercole <zoe.gathercole@ibm.com>
```
* The reviewer should copy the above text into the extended description field when performing the `squash and merge` from this page.
> feat: Update to Kafka 2.8.0

- ui/src/Bootstrap/index.js
**READY**
* When opening this PR, the raiser should set the title of this PR to the first line of their desired commit message, e.g:
```
feat|fix|docs|style|refactor|perf|test|chore: changed function X
```
* The reviewer should ensure that the first commit message field is of this form when performing the `squash and merge` from this page.
```
Further details of the code going into the commit
Contributes to: #XYZ
Closes: #XYZ
Signed-off-by: Your Name <email@address.com>
```
* The reviewer should copy the above text into the extended description field when performing the `squash and merge` from this page.
> feat: replace hardcoded localhost

- pom.xml
Contributes to: mhub/qp-planning#9700
Signed-off-by: JOJO Johnson JOJO.Johnson@ibm.com
> feat: update pom xml

- src/main/java/kafka/vertx/demo/WebSocketServer.java
address NPE while producing messages
Resolves: #366
> chore: address NPE while producing messages
